# This is a sample deployment manifest file for a simple web application.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-portfolio
  labels:
    app: go-webapp-portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-webapp-portfolio
  template:
    metadata:
      labels:
        app: go-webapp-portfolio
    spec:
      containers:
      - name: go-webapp-portfolio
        image: ibrahimsahabi87/go-webapp-portfolio:{{ .Values.image.tag }}
        ports:
        - containerPort: 8080