# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: go-webapp-portfolio
  labels:
    app: go-webapp-portfolio
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: go-webapp-portfolio
  type: ClusterIP
